export const guests = [
  // `plural: true` when the invite addresses more than one guest (couple/family) —
  // controls verb/pronoun agreement in the invite text ("celebrarem"/"vocês" vs "celebrar"/"você").

  /*--------------------------------------------SHE--------------------------------------------*/
  { slug: "adriana-e-afrodite", displayName: "Adriana & Afrodite", plural: true },
  { slug: "agostinho-e-esposa", displayName: "Agostinho & Esposa", plural: true },
  { slug: "antonio-luis-e-esposa", displayName: "António Luís & Esposa", plural: true },
  { slug: "braulio-e-esposa", displayName: "Braúlio & Esposa", plural: true },
  { slug: "buima-e-vanessa", displayName: "Buima & Vanessa", plural: true },
  { slug: "cesaltino-coelho", displayName: "Cesaltino Coelho", plural: false },
  { slug: "didinha-e-esposo", displayName: "Didinha & Esposo", plural: true },
  { slug: "edelson-e-noiva", displayName: "Edelson & Noiva", plural: true },
  { slug: "esperanca-e-esposo", displayName: "Esperança & Esposo", plural: true },
  { slug: "francisco-e-esposa", displayName: "Francisco & Esposa", plural: true },
  { slug: "jorge-e-marlon", displayName: "Jorge & Marlon", plural: true },
  { slug: "helio-e-esposa", displayName: "Hélio & Esposa", plural: true },
  { slug: "iracelmo-e-esposa", displayName: "Iracelmo & Esposa", plural: true },
  { slug: "irina-e-esposo", displayName: "Irina & Esposo", plural: true },
  { slug: "lui-e-esposa", displayName: "Lui & Esposa", plural: true },
  { slug: "malik-e-esposa", displayName: "Malik & Esposa", plural: true },
  { slug: "manuel-luis-e-esposa", displayName: "Manuel Luís & Esposa", plural: true },
  { slug: "maria-samba", displayName: "Maria Samba", plural: false },
  { slug: "martinha-silvestre", displayName: "Martinha Silvestre", plural: false },
  { slug: "mauro-anderson", displayName: "Mauro Anderson", plural: false },
  { slug: "miguel-simao-e-esposa", displayName: "Miguel Simão & Esposa", plural: true },
  { slug: "santa-e-rosandre", displayName: "Santa & Rosandre", plural: true },
  { slug: "silvio-e-esposa", displayName: "Sílvio & Esposa", plural: true },
  { slug: "simao-neto-e-esposa", displayName: "Simão Neto & Esposa", plural: true },
  { slug: "tia-angela-e-tio-paulo", displayName: "Tia Ângela & Tio Paulo", plural: true },
  { slug: "tia-belita-e-esposo", displayName: "Tia Belita & Esposo", plural: true },
  { slug: "tia-pretinha-e-acompanhante", displayName: "Tia Pretinha & Acompanhante", plural: true },
  { slug: "tia-fany-e-esposo", displayName: "Tia Fany & Esposo", plural: true },
  { slug: "tia-mabi-e-mario", displayName: "Tia Mabi & Mário", plural: true },
  { slug: "tio-coelho-e-esposa", displayName: "Tio Coelho & Esposa", plural: true },
  { slug: "tio-duma-e-esposa", displayName: "Tio Duma & Esposa", plural: true },
  { slug: "tio-lemos", displayName: "Tio Lemos", plural: false },
  { slug: "tio-martinho-e-esposa", displayName: "Tio Martinho & Esposa", plural: true },
  { slug: "tio-nelo-e-esposa", displayName: "Tio Nelo & Esposa", plural: true },
  { slug: "tio-bernardino-e-esposa", displayName: "Tio Bernardino & Esposa", plural: true },
  { slug: "tio-leandro-e-esposa", displayName: "Tio Leandro & Esposa", plural: true },
  { slug: "tio-nepy", displayName: "Tio Nepy", plural: false },
  { slug: "tia-carol", displayName: "Tia Carol", plural: false },
  { slug: "tio-toy-e-esposa", displayName: "Tio Toy & Esposa", plural: true },
  { slug: "vanusa-manuel", displayName: "Vanusa Manuel", plural: false },
  { slug: "victor-e-esposa", displayName: "Victor & Esposa", plural: true },
  { slug: "walter-e-esposa", displayName: "Walter & Esposa", plural: true },
  { slug: "wilson-e-esposa", displayName: "Wilson & Esposa", plural: true },
  { slug: "xavier-e-esposa", displayName: "Xavier & Esposa", plural: true },
  { slug: "yola-e-esposo", displayName: "Yola & Esposo", plural: true },
  { slug: "yuli-e-esposa", displayName: "Yuli & Esposa", plural: true },
  { slug: "yuri-e-esposa", displayName: "Yuri & Esposa", plural: true },
  { slug: "silvia-e-noivo", displayName: "Sílvia & Noivo", plural: true },
  { slug: "adilma-e-noivo", displayName: "Adilma & Noivo", plural: true },
  { slug: "elizabeth-e-noivo", displayName: "Elizabeth & Noivo", plural: true },
  { slug: "mauro-e-marilu", displayName: "Mauro & Marilu", plural: true },
  { slug: "soemy-santos", displayName: "Soemy Santos", plural: false },
  { slug: "vita-ngombo", displayName: "Vita Ngombo", plural: false },
  { slug: "lopes-e-noiva", displayName: "Lopes & Noiva", plural: true },
  { slug: "duda-maria", displayName: "Duda Maria", plural: false },
  { slug: "erivaldo-lopes", displayName: "Erivaldo Lopes", plural: false },
  { slug: "santo-david", displayName: "Santo David", plural: false },
  { slug: "nathan-kati", displayName: "Nathan Kati", plural: false },
  { slug: "jedeao-antonio", displayName: "Jedeão António", plural: false },
  { slug: "djamila-cruz", displayName: "Djamila Cruz", plural: false },
  { slug: "arnaldo-vanga", displayName: "Arnaldo Vanga", plural: false },
  { slug: "ana-camalata-e-esposo", displayName: "Ana Camalata & Esposo", plural: true },
  { slug: "cesario-e-esposa", displayName: "Cesário & Esposa", plural: true },
  { slug: "osvaldo-e-frene", displayName: "Osvaldo & Frene", plural: true },
  { slug: "kuanzambi-daniel", displayName: "Kuanzambi Daniel", plural: false },
  { slug: "domingas-e-leticia", displayName: "Domingas & Letícia", plural: true },
  { slug: "djamila-e-acompanhante", displayName: "Djamila & Acompanhante", plural: true },
  { slug: "aurora-auria", displayName: "Aurora Auria", plural: false },
  { slug: "laureth-e-silvia", displayName: "Laureth & Sílvia", plural: true },
  { slug: "marineth-guiomar", displayName: "Marineth Guiomar", plural: false },
  { slug: "jennifer-nascimento", displayName: "Jennifer Nascimento", plural: false },
  { slug: "edmilson-e-acompanhante", displayName: "Edmilson & Acompanhante", plural: true},
  { slug: "claudio-e-acompanhante", displayName: "Cláudio & Acompanhante", plural: true },
  { slug: "aylton-e-acompanhante", displayName: "Aylton & Acompanhante", plural: true },
  { slug: "wilma-e-esposo", displayName: "Wilma & Esposo", plural: true },
  { slug: "ana-carina", displayName: "Ana Carina", plural: false },
  { slug: "delcio-paulo", displayName: "Délcio Paulo", plural: false },
  { slug: "rafael-ngunga", displayName: "Rafael Ngunga", plural: false },
  { slug: "serafina-e-esposo", displayName: "Serafina & Esposo", plural: true },
  { slug: "alia-agostinho", displayName: "Alia Agostinho", plural: false },
  { slug: "jane-azevedo", displayName: "Jane Azevedo", plural: false },
  { slug: "auria-mateus", displayName: "Auria Mateus", plural: false },
  { slug: "adriana-joao", displayName: "Adriana João", plural: false },
  { slug: "miguel-benza", displayName: "Miguel Benza", plural: false },

  /*--------------------------------------------HE--------------------------------------------*/
  // Mamoite - Irmãos
  { slug: "agostinho-neto", displayName: "Agostinho Neto", plural: false },
  { slug: "maria-agostinho", displayName: "Maria Agostinho", plural: false },
  { slug: "ludovina-agostinho", displayName: "Ludovina Agostinho", plural: false },
  { slug: "pedro-agostinho-e-esposa", displayName: "Pedro Agostinho & Esposa", plural: true },

  // Mamoite - Primos
  { slug: "samuel-figueiredo-e-esposa", displayName: "Samuel Figueiredo & Esposa", plural: true },
  { slug: "xaxa", displayName: "Xaxa", plural: false }, // TODO: Replace placeholder when name is known
  { slug: "samuel-machado-e-esposa", displayName: "Samuel Machado & Esposa", plural: true },
  { slug: "margarida-lelo-e-esposo", displayName: "Margarida Lelo & Esposo", plural: true },
  { slug: "maria-lelo-e-esposo", displayName: "Maria Lelo & Esposo", plural: true },
  { slug: "conceicao-paulo", displayName: "Conceição Paulo", plural: false },

  // Mamoite - Sobrinhos
  { slug: "adilson-costa-e-esposa", displayName: "Adilson Costa & Esposa", plural: true },
  { slug: "antonio-lemos-e-esposa", displayName: "António Lemos & Esposa", plural: true },
  { slug: "emanuel-gaspar-e-esposa", displayName: "Emanuel Gaspar & Esposa", plural: true },
  { slug: "weza-benilde", displayName: "Weza Benilde", plural: false },
  { slug: "edmilson-da-costa-e-esposa", displayName: "Edmilson da Costa & Esposa", plural: true },
  { slug: "branca-da-costa", displayName: "Branca da Costa", plural: false },
  { slug: "ariclenes-da-costa-e-esposa", displayName: "Ariclenes da Costa & Esposa", plural: true },
  { slug: "anderson-agostinho", displayName: "Anderson Agostinho", plural: false },
  { slug: "ketsia-marilda", displayName: "Ketsia Marilda", plural: false },
  { slug: "benilde-gamboa-e-esposo", displayName: "Benilde Gâmboa & Esposo", plural: true },
  { slug: "jorge-e-rita", displayName: "Jorge & Rita", plural: true },
  { slug: "belmiro-correia", displayName: "Belmiro Correia", plural: false },

  // Mamoite - Filhos
  { slug: "balbina-francisco-e-esposo", displayName: "Balbina Francisco & Esposo", plural: true },
  { slug: "ianique-e-petaias", displayName: "Ianique & Petaias", plural: true },
  { slug: "emanuel-silva", displayName: "Emanuel Silva", plural: false },
  { slug: "lourenco-valdir", displayName: "Lourenço Valdir", plural: false },
  { slug: "mario-giovani", displayName: "Mário Giovani", plural: false },

  // Papoite
  { slug: "tony-e-esposa", displayName: "Tony & Wife", plural: true },
  { slug: "manuela", displayName: "Manuela", plural: false },
  { slug: "sonia", displayName: "Sonia", plural: false },
  { slug: "matias-e-esposa", displayName: "Matias & Wife", plural: true },
  { slug: "rosa-morgado-e-esposo", displayName: "Rosa Morgado & Esposo", plural: true },
  { slug: "jorge-silva-e-esposa", displayName: "Jorge Silva & Esposa", plural: true },

  // TODO: Replace placeholders when names are known
  { slug: "convidado-papoite-1", displayName: "X", plural: false },
  { slug: "convidado-papoite-2", displayName: "X", plural: false },
  { slug: "convidado-papoite-3", displayName: "X", plural: false },
  { slug: "convidado-papoite-4", displayName: "X", plural: false },

  // Me
  { slug: "gilberto-felix", displayName: "Gilberto Félix", plural: false },
  { slug: "sandro-e-carina", displayName: "Sandro & Carina", plural: true },
  { slug: "nelson-e-indira", displayName: "Nelson & Indira", plural: true },
  { slug: "martino-ivaba-e-noiva", displayName: "Martino Ivaba & Noiva", plural: true },
  { slug: "emanuel-jorge", displayName: "Emanuel Jorge", plural: false },
  { slug: "rufino-domingos", displayName: "Rufino Domingos", plural: false },
  { slug: "hilquias-chitazo", displayName: "Hilquias Chitazo", plural: false },
  { slug: "rui-neto", displayName: "Rui Neto", plural: false },
  { slug: "horacio-mulaza-e-esposa", displayName: "Horácio Mulaza & Esposa", plural: true },
  { slug: "jorge-goncalves", displayName: "Jorge Gonçalves", plural: false },
  { slug: "hubbem-da-silva-e-esposa", displayName: "Hubbem da Silva & Esposa", plural: true },
] as const;