export const guests = [
  // `plural: true` when the invite addresses more than one guest (couple/family) —
  // controls verb/pronoun agreement in the invite text ("celebrarem"/"vocês" vs "celebrar"/"você").

  /*--------------------------------------------SHE--------------------------------------------*/
  { slug: "adriana-e-afrodite", displayName: "Adriana & Afrodite", plural: true },
  { slug: "agostinho-e-esposa", displayName: "Agostinho & Esposa", plural: true },
  { slug: "antonio-luis-e-esposa", displayName: "António Luís & Esposa", plural: true },
  { slug: "braulio-e-esposa", displayName: "Braúlio & Esposa", plural: true },
  { slug: "buima-e-vanessa", displayName: "Buima & Vanessa", plural: true },
  { slug: "cesaltino-coelho", displayName: "Cesaltino Coelho", plural: false },
  { slug: "didinha-e-esposo", displayName: "Didinha & Esposo", plural: true },
  { slug: "edelson-e-noiva", displayName: "Edelson & Noiva", plural: true },
  { slug: "esperanca-e-esposo", displayName: "Esperança & Esposo", plural: true },
  { slug: "francisco-e-esposa", displayName: "Francisco & Esposa", plural: true },
  { slug: "jorge-e-marlon", displayName: "Jorge & Marlon", plural: true },
  { slug: "helio-e-esposa", displayName: "Hélio & Esposa", plural: true },
  { slug: "iracelmo-e-esposa", displayName: "Iracelmo & Esposa", plural: true },
  { slug: "irina-e-esposo", displayName: "Irina & Esposo", plural: true },
  { slug: "lui-e-esposa", displayName: "Lui & Esposa", plural: true },
  { slug: "malik-e-esposa", displayName: "Malik & Esposa", plural: true },
  { slug: "manuel-luis-e-esposa", displayName: "Manuel Luís & Esposa", plural: true },
  { slug: "maria-samba", displayName: "Maria Samba", plural: false },
  { slug: "martinha-silvestre", displayName: "Martinha Silvestre", plural: false },
  { slug: "mauro-anderson", displayName: "Mauro Anderson", plural: false },
  { slug: "miguel-simao-e-esposa", displayName: "Miguel Simão & Esposa", plural: true },
  { slug: "santa-e-rosandre", displayName: "Santa & Rosandre", plural: true },
  { slug: "silvio-e-esposa", displayName: "Sílvio & Esposa", plural: true },
  { slug: "simao-neto-e-esposa", displayName: "Simão Neto & Esposa", plural: true },
  { slug: "tia-angela-e-tio-paulo", displayName: "Tia Ângela & Tio Paulo", plural: true },
  { slug: "tia-belita-e-esposo", displayName: "Tia Belita & Esposo", plural: true },
  { slug: "tia-pretinha-e-acompanhante", displayName: "Tia Pretinha & Acompanhante", plural: true },
  { slug: "tia-fany-e-esposo", displayName: "Tia Fany & Esposo", plural: true },
  { slug: "adriana-e-afrodite", displayName: "Adriana & Afrodite", plural: true },
  { slug: "agostinho-e-esposa", displayName: "Agostinho & Esposa", plural: true },
  { slug: "antonio-luis-e-esposa", displayName: "António Luís & Esposa", plural: true },
  { slug: "braulio-e-esposa", displayName: "Braúlio & Esposa", plural: true },
  { slug: "buima-e-vanessa", displayName: "Buima & Vanessa", plural: true },
  { slug: "cesaltino-coelho", displayName: "Cesaltino Coelho", plural: false },
  { slug: "didinha-e-esposo", displayName: "Didinha & Esposo", plural: true },
  { slug: "edelson-e-noiva", displayName: "Edelson & Noiva", plural: true },
  { slug: "esperanca-e-esposo", displayName: "Esperança & Esposo", plural: true },
  { slug: "francisco-e-esposa", displayName: "Francisco & Esposa", plural: true },
  { slug: "jorge-e-marlon", displayName: "Jorge & Marlon", plural: true },
  { slug: "helio-e-esposa", displayName: "Hélio & Esposa", plural: true },
  { slug: "iracelmo-e-esposa", displayName: "Iracelmo & Esposa", plural: true },
  { slug: "irina-e-esposo", displayName: "Irina & Esposo", plural: true },
  { slug: "lui-e-esposa", displayName: "Lui & Esposa", plural: true },
  { slug: "malik-e-esposa", displayName: "Malik & Esposa", plural: true },
  { slug: "manuel-luis-e-esposa", displayName: "Manuel Luís & Esposa", plural: true },
  { slug: "maria-samba", displayName: "Maria Samba", plural: false },
  { slug: "martinha-silvestre", displayName: "Martinha Silvestre", plural: false },
  { slug: "mauro-anderson", displayName: "Mauro Anderson", plural: false },
  { slug: "miguel-simao-e-esposa", displayName: "Miguel Simão & Esposa", plural: true },
  { slug: "santa-e-rosandre", displayName: "Santa & Rosandre", plural: true },
  { slug: "silvio-e-esposa", displayName: "Sílvio & Esposa", plural: true },
  { slug: "simao-neto-e-esposa", displayName: "Simão Neto & Esposa", plural: true },
  { slug: "tia-angela-e-tio-paulo", displayName: "Tia Ângela & Tio Paulo", plural: true },
  { slug: "tia-belita-e-esposo", displayName: "Tia Belita & Esposo", plural: true },
  { slug: "tia-pretinha-e-acompanhante", displayName: "Tia Pretinha & Acompanhante", plural: true },
  { slug: "tia-fany-e-esposo", displayName: "Tia Fany & Esposo", plural: true },
  { slug: "adriana-e-afrodite", displayName: "Adriana & Afrodite", plural: true },
  { slug: "agostinho-e-esposa", displayName: "Agostinho & Esposa", plural: true },
  { slug: "antonio-luis-e-esposa", displayName: "António Luís & Esposa", plural: true },
  { slug: "braulio-e-esposa", displayName: "Braúlio & Esposa", plural: true },
  { slug: "buima-e-vanessa", displayName: "Buima & Vanessa", plural: true },
  { slug: "cesaltino-coelho", displayName: "Cesaltino Coelho", plural: false },
  { slug: "didinha-e-esposo", displayName: "Didinha & Esposo", plural: true },
  { slug: "edelson-e-noiva", displayName: "Edelson & Noiva", plural: true },
  { slug: "esperanca-e-esposo", displayName: "Esperança & Esposo", plural: true },
  { slug: "francisco-e-esposa", displayName: "Francisco & Esposa", plural: true },
  { slug: "jorge-e-marlon", displayName: "Jorge & Marlon", plural: true },
  { slug: "helio-e-esposa", displayName: "Hélio & Esposa", plural: true },
  { slug: "iracelmo-e-esposa", displayName: "Iracelmo & Esposa", plural: true },
  { slug: "irina-e-esposo", displayName: "Irina & Esposo", plural: true },
  { slug: "lui-e-esposa", displayName: "Lui & Esposa", plural: true },
  { slug: "malik-e-esposa", displayName: "Malik & Esposa", plural: true },
  { slug: "manuel-luis-e-esposa", displayName: "Manuel Luís & Esposa", plural: true },
  { slug: "maria-samba", displayName: "Maria Samba", plural: false },
  { slug: "martinha-silvestre", displayName: "Martinha Silvestre", plural: false },
  { slug: "mauro-anderson", displayName: "Mauro Anderson", plural: false },
  { slug: "miguel-simao-e-esposa", displayName: "Miguel Simão & Esposa", plural: true },
  { slug: "santa-e-rosandre", displayName: "Santa & Rosandre", plural: true },
  { slug: "silvio-e-esposa", displayName: "Sílvio & Esposa", plural: true },
  { slug: "simao-neto-e-esposa", displayName: "Simão Neto & Esposa", plural: true },
  { slug: "tia-angela-e-tio-paulo", displayName: "Tia Ângela & Tio Paulo", plural: true },
  { slug: "tia-belita-e-esposo", displayName: "Tia Belita & Esposo", plural: true },
  { slug: "tia-pretinha-e-acompanhante", displayName: "Tia Pretinha & Acompanhante", plural: true },
  { slug: "tia-fany-e-esposo", displayName: "Tia Fany & Esposo", plural: true },

  /*--------------------------------------------HE--------------------------------------------*/
  // Mamoite - Irmãos
  { slug: "agostinho-neto", displayName: "Agostinho Neto", plural: false },
  { slug: "maria-agostinho", displayName: "Maria Agostinho", plural: false },
  { slug: "ludovina-agostinho", displayName: "Ludovina Agostinho", plural: false },
  { slug: "pedro-agostinho-e-esposa", displayName: "Pedro Agostinho & Esposa", plural: true },

  // Mamoite - Primos
  { slug: "samuel", displayName: "Samuel", plural: false }, // TODO: Replace placeholder when name is known
  { slug: "xaxa", displayName: "Xaxa", plural: false }, // TODO: Replace placeholder when name is known
  { slug: "dadao-e-esposa", displayName: "Dadão & Esposa", plural: true }, // TODO: Replace placeholder when name is known
  { slug: "margarida-e-marido", displayName: "Margarida & Marido", plural: true },
  { slug: "tia-ita", displayName: "Tia Ita", plural: false }, // TODO: Replace placeholder when name is known
  { slug: "mae-da-petaias", displayName: "Mãe da Petaias", plural: false }, // TODO: Replace placeholder when name is known

  // Mamoite - Sobrinhos
  { slug: "adilson-costa-e-esposa", displayName: "Adilson Costa & Esposa", plural: true },
  { slug: "antonio-lemos-e-esposa", displayName: "António Lemos & Esposa", plural: true },
  { slug: "emanuel-gaspar-e-esposa", displayName: "Emanuel Gaspar & Esposa", plural: true },
  { slug: "weza-benilde", displayName: "Weza Benilde", plural: false },
  { slug: "edmilson-da-costa-e-esposa", displayName: "Edmilson da Costa & Esposa", plural: true },
  { slug: "branca-da-costa", displayName: "Branca da Costa", plural: false },
  { slug: "ariclenes-da-costa-e-esposa", displayName: "Ariclenes da Costa & Esposa", plural: true },
  { slug: "andelson-agostinho", displayName: "Andelson Agostinho", plural: false },
  { slug: "ketsia-marilda", displayName: "Ketsia Marilda", plural: false },
  { slug: "benilde-gamboa-e-esposo", displayName: "Benilde Gâmboa & Esposo", plural: true },
  { slug: "jorge-e-rita", displayName: "Jorge & Rita", plural: true },
  { slug: "belmiro-correia", displayName: "Belmiro Correia", plural: false },

  // Mamoite - Filhos
  { slug: "balbina-francisco-e-esposo", displayName: "Balbina Francisco & Esposo", plural: true },
  { slug: "ianique-e-petaias", displayName: "Ianique & Petaias", plural: true },
  { slug: "emanuel-silva", displayName: "Emanuel Silva", plural: false },
  { slug: "lourenco-valdir", displayName: "Lourenço Valdir", plural: false },
  { slug: "mario-giovani", displayName: "Mário Giovani", plural: false },

  // Papoite
  { slug: "tony-e-esposa", displayName: "Tony & Wife", plural: true },
  { slug: "manuela", displayName: "Manuela", plural: false },
  { slug: "sonia", displayName: "Sonia", plural: false },
  { slug: "matias-e-esposa", displayName: "Matias & Wife", plural: true },
  { slug: "jorge-silva-e-esposa", displayName: "Jorge Silva & Esposa", plural: true },
  { slug: "osvaldo-silva-e-esposa", displayName: "Osvaldo Silva & Esposa", plural: true },
  { slug: "rosa-morgado-e-esposo", displayName: "Rosa Morgado & Esposo", plural: true },

  // TODO: Replace placeholders when names are known
  { slug: "convidado-papoite-1", displayName: "X", plural: false },
  { slug: "convidado-papoite-2", displayName: "X", plural: false },
  { slug: "convidado-papoite-3", displayName: "X", plural: false },
  { slug: "convidado-papoite-4", displayName: "X", plural: false },

  // Me
  { slug: "gilberto-felix", displayName: "Gilberto Félix", plural: false },
  { slug: "sandro-e-carina", displayName: "Sandro & Carina", plural: true },
  { slug: "nelson-e-indira", displayName: "Nelson & Indira", plural: true },
  { slug: "martino-ivaba-e-noiva", displayName: "Martino Ivaba & Noiva", plural: true },
  { slug: "emanuel-jorge", displayName: "Emanuel Jorge", plural: false },
  { slug: "rufino-domingos", displayName: "Rufino Domingos", plural: false },
  { slug: "hilquias-chitazo", displayName: "Hilquias Chitazo", plural: false },
  { slug: "rui-neto", displayName: "Rui Neto", plural: false },
  { slug: "horacio-mulaza-e-esposa", displayName: "Horácio Mulaza & Esposa", plural: true },
  { slug: "jorge-goncalves", displayName: "Jorge Gonçalves", plural: false },
  { slug: "edson-tomas-e-esposa", displayName: "Edson Tomás & Esposa", plural: true },
] as const;